#!/bin/sh
echo "$(date "+%F %T"): 正在下载adblockplus规则..."
wget-ssl --quiet --no-check-certificate https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf -O /tmp/adlist.txt
if [ "$?" == "0" ]; then
	#grep ^\|\|[^\*]*\^$ /tmp/adlist.txt | sed -e 's:||:address\=\/:' -e 's:\^:/0\.0\.0\.0:' > /tmp/dnsmasq.adblock
	#grep ^[^\#] /tmp/adlist.txt | sed 's/$/&0.0.0.0/g' > /tmp/dnsmasq.adblock
	sed '/^address.*$/s//&0.0.0.0/g' /tmp/adlist.txt > /tmp/dnsmasq.adblock
	rm -f /tmp/adlist.txt
	#diff /tmp/dnsmasq.adblock /usr/share/koolproxy/dnsmasq.adblock >/dev/null
	local=`cat /tmp/dnsmasq.adblock  | sed -n '2p'`
	local1=`cat /usr/share/koolproxy/dnsmasq.adblock  | sed -n '2p'`

	echo "$(date "+%F %T"): adblockplus规则 在线版本号：" ${local#*=} 
	echo "$(date "+%F %T"): adblockplus规则 本地版本号：" ${local1#*=}

if [ $local != $local1 ];then
	echo "$(date "+%F %T"): 检测到adblockplus规则有更新，开始更新规则！" 
	echo "$(date "+%F %T"): 将临时文件覆盖到adblockplus规则文件" 
	sed -i '/youku/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
	sed -i '/[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
	mv /tmp/dnsmasq.adblock /usr/share/koolproxy/dnsmasq.adblock
	echo "$(date "+%F %T"): adblockplus规则转换完成，应用新规则。"
	echo "$(date "+%F %T"): 重启dnsmasq进程"
	/etc/init.d/dnsmasq restart > /dev/null 2>&1
	return 0
else
	 echo "$(date "+%F %T"): adblockplus规则和服务器规则相同，无需更新!" 
	 rm -f /tmp/dnsmasq.adblock
   	
fi
else
	echo "$(date "+%F %T"): 获取在线版本时出现错误! "
	[ -f /tmp/adlist.txt ] && rm -f /tmp/adlist.txt
	return 1
fi
